language: node_js
node_js: "stable"

dist: bionic

before_install:
  - stty cols 80

addons:
  firefox: latest
  chrome: stable

before_script:
  - yarn start:backend
  - sleep 2 # give backend service some time to start

scirpt: yarn tests:backend
